### ISSUE TITLE
有一种突破方法

### ISSUE THREAD

**Issue by a90120411** [theajack/disable-devtool#1]
浏览器：Chrome

1、先打开一个空白页，并打开开发者工具，在开发者者工具的Network面板，勾选 Preserve Log。

2、Console中使用 window.location.href="https://theajack.gitee.io/disable-devtool/" ，访问测试页面。

3、页面正常被库拦截关闭，但Network中是可以看到 https://cdn.jsdelivr.net/npm/disable-devtool@latest/disable-devtool.min.js 的引用代码的。

4、右键这个JS文件，选择 Block request URL，可以将这个库的请求给屏蔽。

5、再次打开页面，即可突破限制。

------------

如果是将这个库和其它JS文件打包后，通过Source面板的 Overrides 功能改写应该也是可以突破的。这个库已经可以阻挡绝大多数的人调试页面了，还是很不错了。

**Comment by theajack** [comment]
确实可以 那这个没办法了 相当于是让浏览器禁止加载了这个库。

可以稍微弥补一下的方法就是把这个库打包到你的代码一起 这样禁用就一起禁用了，啥也加载不出来。

**Comment by a90120411** [comment]
> 确实可以那这个没办法了相当于是让浏览器禁止加载了这个库。
> 
> 可以稍微补充一下的方法就是把这个库打包到你的代码一起这样替换就一起替换了，啥也加载不出来。

你好像没看到我在分割线下面写的内容，防不住的。

**Comment by theajack** [comment]
@a90120411 
哦哦 是的
其实任http请求的内容就是你没办法阻止别人拿到，直接拦截http请求就什么都可以获取到了 只是尽量干扰吧
这个issue我关了哈
