### ISSUE TITLE
Disable DevTool URL BUG

### ISSUE THREAD

**Issue by LaiYueTing** [theajack/disable-devtool#10]
In the new version, although Google Chrome DevTool has been successfully blocked, some customers who browse the web will be unexpectedly redirected to the Disable DevTool URL page. Is there a way to fix this problem?

Version 0.1.3 will not have this problem, only after version 0.1.4 will this BUG appear

**Comment by theajack** [comment]
Please update to the version 0.1.5



发自我的iPhone


------------------ Original ------------------
From: LaiYueTing ***@***.***&gt;
Date: Thu,Jul 29,2021 4:23 AM
To: theajack/disable-devtool ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [theajack/disable-devtool] Disable DevTool URL BUG (#10)





 
In the new version, although Google Chrome’s DevTool has been successfully blocked, some customers who browse the web will be unexpectedly redirected to the Disable DevTool URL page. Is there a way to fix this problem?
 
Version 0.1.3 will not have this problem, only after version 0.1.4 will this BUG appear

**Comment by LaiYueTing** [comment]
> Please update to the version 0.1.5 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: LaiYueTing ***@***.***&gt; Date: Thu,Jul 29,2021 4:23 AM To: theajack/disable-devtool ***@***.***&gt; Cc: Subscribed ***@***.***&gt; Subject: Re: [theajack/disable-devtool] Disable DevTool URL BUG (#10) In the new version, although Google Chrome’s DevTool has been successfully blocked, some customers who browse the web will be unexpectedly redirected to the Disable DevTool URL page. Is there a way to fix this problem? Version 0.1.3 will not have this problem, only after version 0.1.4 will this BUG appear — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

This BUG will also appear in version 0.1.5

**Comment by theajack** [comment]
@LaiYueTing 
Can this url reproduce the bug? It applied v0.1.5
https://www.theajack.com/disable-devtool

And what type and version of your computer's operating system？

**Comment by LaiYueTing** [comment]
@theajack 
I did not encounter this bug, but some users said that they would keep jumping.

**Comment by theajack** [comment]
Fixed! Please upgrade to Version 0.1.7. @LaiYueTing
