### ISSUE TITLE
disable-devtool script inside an iframe auto redirects to the specified URL page

### ISSUE THREAD

**Issue by imranhome1** [theajack/disable-devtool#11]
Hi, the disable-devtool script inside an iframe auto redirects to the specified URL page instead it should wait if there is any activity like using of devtools on the parent page.

**Comment by imranhome1** [comment]
I have moved the script outside the iframe and found it detect it as an open tool just like inspect element and redirect to the URL.

Can you please fix this to avoid iframe.

**Comment by karchung0930** [comment]
I got the same issue, where the page with iframe will be redirected back to the last page. Please fix this bug

**Comment by milindpatel63** [comment]
Any way to fix this issue? :(

**Comment by milindpatel63** [comment]
Here's my workaround for this
This will disable the script when loaded in an iframe


<script nonce="">
function inIframe () {
    try {
        return window.self !== window.top;
    } catch (e) {
        return true;
    }
}
window.onload = function() {
    var s = document.createElement('script');
    s.type = 'text/javascript';
    s.src = 'https://cdn.jsdelivr.net/npm/disable-devtool@latest/disable-devtool.min.js';
    if(!inIframe()){
        s.setAttribute('disable-devtool-auto','');
    	s.setAttribute('url','https://google.com');
    }
    s.setAttribute('nonce','');
    try {
      document.body.appendChild(s);
    } catch (e) {
      document.body.appendChild(s);
    }
  }
</script>

**Comment by josephmiller2000** [comment]
@milindpatel63 Am not sure, disabling the script through iframe is not a workaround. We need a way to make it work along with iframe and get this issue fixed.

**Comment by theajack** [comment]
Fixed! Please upgrade to Version 0.1.7.

**Comment by theajack** [comment]
@imranhome1 @josephmiller2000 @karchung0930 @milindpatel63 

Fixed! Please upgrade to Version 0.1.9
