### ISSUE TITLE
mac谷歌遇到过闪退

### ISSUE THREAD

**Issue by qihaimi** [theajack/disable-devtool#12]
<script 
	disable-devtool-auto 
	src='https://cdn.jsdelivr.net/npm/disable-devtool@latest/disable-devtool.min.js' 
	disable-menu='true'
	></script>

引用在页面后，遇到过闪退，点击跳转下一页面(也插入了该代码)点击无效。

**Comment by theajack** [comment]
Fixed! Please upgrade to Version 0.1.7.
