### ISSUE TITLE
叮咚~ 新问题~

### ISSUE THREAD

**Issue by qihaimi** [theajack/disable-devtool#17]
一行代码搞定禁用web开发者工具

在浏览器网站设置里 JavaScript 禁止 后，有没有什么办法，让访客在把 JavaScript 禁止后无法正常浏览网页或者直接空白呢？

我知道这或许跟网站本身结构有关，但是我们工具是 一行代码搞定禁用web开发者工具 ，我觉得应该考虑一下这个建议。

**Comment by theajack** [comment]
我是有想过这个问题的 但是由于浏览器设置了disable javascript，所以理论上来说js就没有任何行为了，所以这个库当然也没有办法让网页异常或者空白。后续我会继续思考这个问题的，或者你有方案建议或者其他站点有类似功能可以提供一点帮助，谢谢

**Comment by theajack** [comment]
有一种可行的方案是你的站点的html是通过js动态加载上去的，js没法执行 网页自然就是空白的，但是他人还是可以从sources里面拿到站点的所有依赖文件
