### ISSUE TITLE
本地开发环境生效，测试环境\生产环境无效

### ISSUE THREAD

**Issue by A1len-L** [theajack/disable-devtool#18]

**Comment by A1len-L** [comment]
我在vue项目中使用了disable-devtool，本地是好的，但是发布之后测试或者生产环境无法通过键盘操作打开控制台，但是可以通过点击 开发者工具 打开，或者在某一页面打开控制台然后再复制进去链接也可以，二者都不会发生跳转。

**Comment by theajack** [comment]
那应该是没有生效的 方便看一下你是如何调用的吗

**Comment by A1len-L** [comment]
import disableDevtool from 'disable-devtool'
disableDevtool({
    tkName: 'ddtk',
    md5: disableDevtool.md5('qwer')
})
是这样调用的。
我用的是mac，Chrome版本96.0.4664.110，在本地是各种方式都打不开控制台，测试或者生产环境通过键盘或者鼠标右键是打不开的，但是可以通过更多工具 => 开发者工具打开，或者在某一页面先打开控制台然后再复制进去链接也可以，不会发生跳转，感觉是部分生效。测试用的windows表现正常，都打不开。

**Comment by A1len-L** [comment]
而且很奇怪，https://theajack.gitee.io/disable-devtool/ 这个链接我的电脑各种方式也打不开控制台。

**Comment by theajack** [comment]
> 而且很奇怪，https://theajack.gitee.io/disable-devtool/ 这个链接我的电脑各种方式也打不开控制台。

@A1len-L 这个有点奇怪 检查一下你安装的版本号是最新的吗 0.1.12

**Comment by theajack** [comment]
如果版本没有问题可以使用CDN方式引用一下试试，也有可能是打包过程中除了问题

```html
<script disable-devtool-auto src='https://cdn.jsdelivr.net/npm/disable-devtool/disable-devtool.min.js'></script>
```

直接引用就行，会自动执行，不需要调用api

**Comment by A1len-L** [comment]
升级到了最新的也不行。公司不让直接引cdn。我再看看吧。

**Comment by A1len-L** [comment]
> 升级到了最新的也不行。公司不让直接引cdn。我再看看吧。

试了一下，cdn没问题。

**Comment by theajack** [comment]
你们代码里面有 hack console.log 方法吗
试着把这段代码放在最顶层调用
```js
import disableDevtool from 'disable-devtool'
disableDevtool({
tkName: 'ddtk',
md5: disableDevtool.md5('qwer')
})
```

**Comment by wuyouw** [comment]
如果在当前页面按F12或是控制台以及右键打开，不要退出当前页面，网址不变，页面内容显示空白，退出调试模式，页面显示正常，像这个网站https://zbp.toyean.com/tpure/一样，应该要怎么设置？

**Comment by wuyouw** [comment]
我的意思，打开调试模式，不是关闭当前页面，而是让当前页面显示空白，退出调试模式时，页面显示正常

**Comment by theajack** [comment]
@wuyouw 
目前没有加这种模式，但是这种模式还是可以在source里面看到源代码文件的，其实不是很好
使用disable-devtool可以通过这样配置来实现这个功能

```js
disableDevtool({
    // ...
    ondevtoolopen(){
        document.documentElement.innerHTML = '';
        console.clear();
    },
    clearIntervalWhenDevOpenTrigger: true,
})
```

具体配置可以参考[文档](https://github.com/theajack/disable-devtool#31-configuration-parameters-when-using-npm)

不过目前没有加 ondevtoolclose 监听，所以实现不了识别到关闭 恢复页面的功能，会考虑加入后续版本更新计划

**Comment by theajack** [comment]
> 升级到了最新的也不行。公司不让直接引cdn。我再看看吧。

@A1len-L 请问你的这个问题解决了吗

**Comment by wuyouw** [comment]
> @wuyouw 目前没有加这种模式，但是这种模式还是可以在source里面看到源代码文件的，其实不是很好 使用disable-devtool可以通过这样配置来实现这个功能
> 
> ```js
> disableDevtool({
>     // ...
>     ondevtoolopen(){
>         document.documentElement.innerHTML = '';
>         console.clear();
>     },
>     clearIntervalWhenDevOpenTrigger: true,
> })
> ```
> 
> 具体配置可以参考[文档](https://github.com/theajack/disable-devtool#31-configuration-parameters-when-using-npm)
> 
> 不过目前没有加 ondevtoolclose 监听，所以实现不了识别到关闭 恢复页面的功能，会考虑加入后续版本更新计划

您提供的方法暂时解决了在原页面打开空白的需求，期待您后续和版本更新，谢谢！

**Comment by theajack** [comment]
@wuyouw 
已增加 `ondevtoolclose` 配置

**Comment by wuyouw** [comment]
> @wuyouw 已增加 `ondevtoolclose` 配置

那这个应该要怎么配置呢？

**Comment by wuyouw** [comment]
> @wuyouw 已增加 `ondevtoolclose` 配置

@theajack 
那这个应该要怎么配置呢？

**Comment by theajack** [comment]
@wuyouw 

```javascript
disableDevtool({
    // ...
    ondevtoolopen(){
        document.documentElement.innerHTML = '';
        console.clear();
    },
    ondevtoolclose(){
        location.reload(),
    },
    clearIntervalWhenDevOpenTrigger: false,
})
```

**Comment by wuyouw** [comment]
> @wuyouw
> 
> ```js
> disableDevtool({
>     // ...
>     ondevtoolopen(){
>         document.documentElement.innerHTML = '';
>         console.clear();
>     },
>     ondevtoolclose(){
>         location.reload(),
>     },
>     clearIntervalWhenDevOpenTrigger: false,
> })
> ```

@theajack 谢谢，我先试试

**Comment by wuyouw** [comment]
> @wuyouw
> 
> ```js
> disableDevtool({
>     // ...
>     ondevtoolopen(){
>         document.documentElement.innerHTML = '';
>         console.clear();
>     },
>     ondevtoolclose(){
>         location.reload(),
>     },
>     clearIntervalWhenDevOpenTrigger: false,
> })
> ```

@theajack 经测试，这个可以满足我的需求了，谢谢！但是需要注意的是这个代码有个报错，我用下面的就可以
> ```js
> disableDevtool({
>     // ...
>     ondevtoolopen(){
>         document.documentElement.innerHTML = '';
>         console.clear();
>     },
>     ondevtoolclose(){
>         location.reload()
>     },
>     clearIntervalWhenDevOpenTrigger: false,
> })
> ```
