### ISSUE TITLE
当前端使用hash路由模式时，search为空，导致绕过禁用失败。

### ISSUE THREAD

**Issue by hankaibo** [theajack/disable-devtool#19]
https://github.com/theajack/disable-devtool/blob/master/src/utils/util.js#L10
如上代码可能获取到空值。

**Comment by theajack** [comment]
@hankaibo 感谢反馈，会加入后续更新计划

**Comment by hankaibo** [comment]
我提了 pr ，如果你修复了，我就把 pr 删除了。顺便也关闭一下本 issue.

**Comment by theajack** [comment]
已经合进去了 感谢
