### ISSUE TITLE
火狐浏览器可以直接从菜单进入控制台

### ISSUE THREAD

**Issue by Yakumo-Yukari** [theajack/disable-devtool#2]
![屏幕截图 2021-01-19 185158](https://user-images.githubusercontent.com/12076232/105025345-2e134900-5a88-11eb-9b2b-47249e2b70af.png)

**Comment by Yakumo-Yukari** [comment]
这样好像就可以看到  网页样式了

**Comment by Yakumo-Yukari** [comment]
好像 QQ浏览器也可以来着 忘记了

**Comment by peiz1104** [comment]
火狐浏览器新打开页面，有时会出现关闭页面现象

**Comment by theajack** [comment]
@Yakumo-Yukari 已修复 请升级到0.0.8使用
