### ISSUE TITLE
当打开控制台时，如何在控制台显示警告信息

### ISSUE THREAD

**Issue by wuyouw** [theajack/disable-devtool#22]
@theajack 当访客使用浏览器开发者工具打开控制台时，如何在控制台显示警告信息，比如显示“本站已启用内容保护”等，我现在在JS里加入了这段警告信息，但是控制台一直显示的是控制台数据已被清除，一至在刷新这个信息

**Comment by theajack** [comment]
@wuyouw 其实最好的保护机制是跳转到其他警告页面去 在当前页面打开打开了控制台 可以从sourecs里面看到源代码文件的

**Comment by theajack** [comment]
所以默认会console.clear 这个目前没办法去掉的 后续可以加一个参数控制要不要每次interval的时候清空控制台

**Comment by wuyouw** [comment]
> @wuyouw 其实最好的保护机制是跳转到其他警告页面去 在当前页面打开打开了控制台 可以从sourecs里面看到源代码文件的

@theajack 那要是这样的话，即使跳转到其他警告页面，是不是也可以从sourecs里面看到源代码文件，或者将网页另存为也可以看到源代码？

**Comment by theajack** [comment]
@wuyouw 
source 里面看不到的 都跳转走了 网页另存为也只能看到html的

不过从前端确实没办法100%限制的 可以通过http请求抓包来获取网页文件的，只能增加获取代码的复杂度

**Comment by wuyouw** [comment]
其实也只能防君子，哈哈！

**Comment by theajack** [comment]
@wuyouw 
已增加 clearLog参数 请升级到0.2.3使用，详情请参见文档或index.d.ts

**Comment by wuyouw** [comment]
好的，谢谢！持续关注中！！！
