### ISSUE TITLE
Wrong detect on Edge browser (iPhone, iPad)

### ISSUE THREAD

**Issue by tungwoodboi** [theajack/disable-devtool#24]
Devtools status is always "open"
Browser: Edge mobile iOS (iPad + iPhone)
Script version: [Lastest ](https://cdn.jsdelivr.net/npm/disable-devtool@latest/disable-devtool.min.js)
Demo: [http://htdesignz.net/disable-devtool-test.html](http://htdesignz.net/disable-devtool-test.html)
Code:
```
DisableDevtool({
 ondevtoolopen: () => {
  statusz.innerText="open"
 },
 ondevtoolclose: () => {
  statusz.innerText="closed"
 },
 disableMenu: !1
});
```

![nx2jxNE](https://user-images.githubusercontent.com/13481173/153183663-0f7716b7-5042-4e7b-a42a-b88dbfd72afb.jpeg)

**Comment by Arthemis97** [comment]
Devtools status is always open in Ubuntu 22.04 chrome
