### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by leothewolf** [theajack/disable-devtool#26]
How can I close the tab whenever some1 attempts to open the dev tools as configured on your site?

**Comment by leothewolf** [comment]
![image](https://user-images.githubusercontent.com/91257665/160265852-63c422d3-89b3-4a6c-8f61-5e83ecc693a7.png)
Checkout this I was able to bypass it on your page.....I just opened the dev tools before opening the site and then opened the site though it navigated me once back to the original page but then again I navigated to the site and it worked!

**Comment by leothewolf** [comment]
![image](https://user-images.githubusercontent.com/91257665/160265928-860273d9-7969-4905-9c6f-bc4a107b8b50.png)
Tried the same thing again but was not succesfull

**Comment by theajack** [comment]
@leothewolf 
Please tell me your browser version

**Comment by leothewolf** [comment]
> @leothewolf Please tell me your browser version

Chrome : 103.0.5060.66

**Comment by theajack** [comment]
Now it works again in new version 0.2.6, please check it again.
@leothewolf
