### ISSUE TITLE
devtool

### ISSUE THREAD

**Issue by qassimfard** [theajack/disable-devtool#35]
not working when opening devtool in seperate window

**Comment by theajack** [comment]
Please tell me your browser version

**Comment by qassimfard** [comment]
edge Version 103.0.1264.77

**Comment by qassimfard** [comment]
also in chrome Version 106.0.5216.6 (Official Build) dev (64-bit)

**Comment by theajack** [comment]
Now it works again in new version 0.2.6, please check it again.
@qassimfard
