### ISSUE TITLE
Embed with the lastest version has no effect with embed/iframe

### ISSUE THREAD

**Issue by ThangMarvel** [theajack/disable-devtool#36]
My homepage: https://marvel-media.net
contains a embed/iframe

I place this code right before </body>
"<script disable-devtool-auto src='https://fastly.jsdelivr.net/npm/disable-devtool@latest/disable-devtool.min.js' url='https://facebook.com/Marvel.Media.meta'></script>"

You can visit my homepage to see only the anti-F12 function is working,
other features like disable right click, disable copy select... are not work !

**Comment by theajack** [comment]
fixed in version 0.3.2
