### ISSUE TITLE
Sometimes it stops working...

### ISSUE THREAD

**Issue by hijuuijj** [theajack/disable-devtool#38]
This script randomly stops working for me in Chrome. One day it works and a while later it doesn't, ignoring the script.

<script disable-devtool-auto src='https://cdn.jsdelivr.net/npm/disable-devtool@latest/disable-devtool.min.js'></script>

I'm using Windows 11 and Chrome 103.0.5060.114

**Comment by theajack** [comment]
Now it works again in new version 0.2.6, please check it again.
@hijuuijj
