### ISSUE TITLE
升级到0.8后Firefox依然可以进入开发者工具

### ISSUE THREAD

**Issue by Yakumo-Yukari** [theajack/disable-devtool#4]
![1](https://user-images.githubusercontent.com/12076232/105568020-54c7cd00-5d71-11eb-8595-c1111538d679.png)
![2](https://user-images.githubusercontent.com/12076232/105568026-58f3ea80-5d71-11eb-9f2c-a451d7732a55.png)
![3](https://user-images.githubusercontent.com/12076232/105568028-598c8100-5d71-11eb-883d-d66ac863a247.png)

菜单进入查看器后 可以看到页面还有网络资源

**Comment by theajack** [comment]
https://theajack.gitee.io/disable-devtool/

你用这个页面试试

或者你命令行运行 DisableDevtool.version 看是多少，0.0.7才是对的

0.0.8只是更新了readme

**Comment by Yakumo-Yukari** [comment]
> https://theajack.gitee.io/disable-devtool/
> 
> 你用这个页面试试
> 
> 或者你命令行运行 DisableDevtool.version 看是多少，0.0.7才是对的
> 
> 0.0.8只是更新了readme

因为你在上一个问题贴里说上级到0.8 我就直接用yarn升级到最新版本了

**Comment by Yakumo-Yukari** [comment]
非法

> https://theajack.gitee.io/disable-devtool/
> 
> 你用这个页面试试
> 
> 或者你命令行运行 DisableDevtool.version 看是多少，0.0.7才是对的
> 
> 0.0.8只是更新了readme



> https://theajack.gitee.io/disable-devtool/
> 
> 你用这个页面试试
> 
> 或者你命令行运行 DisableDevtool.version 看是多少，0.0.7才是对的
> 
> 0.0.8只是更新了readme

大佬你给的这个测试网站 也可以进入到  查看器 但是不会显示元素样式   你用的是0.6  你是怎么配置的

我切换到0.7一样会进入查看器 会出现样式表  但是不会跳转到设定好的网址  我就配置了一个跳转网址  只有进入控制台才会跳转在在Firefox下查看器和网络里不会跳转

**Comment by Yakumo-Yukari** [comment]
![20210123174740](https://user-images.githubusercontent.com/12076232/105575053-a2f5c400-5da3-11eb-8f1b-081b4af8aab8.png)
你给的测试地址

**Comment by theajack** [comment]
![image](https://user-images.githubusercontent.com/23377279/105575634-071a8700-5da8-11eb-947e-d27b67285054.png)

0.6可能是cdn有缓存 需要时0.7才对 安装的是0.8其实这个值也是0.7，0.8只是改了readme，version我给忘了~

你能给一个线上demo我看看 我这边测起来是正常的

**Comment by Yakumo-Yukari** [comment]
> ![image](https://user-images.githubusercontent.com/23377279/105575634-071a8700-5da8-11eb-947e-d27b67285054.png)
> 
> 0.6可能是cdn有缓存 需要时0.7才对 安装的是0.8其实这个值也是0.7，0.8只是改了readme，version我给忘了~
> 
> 你能给一个线上demo我看看 我这边测起来是正常的

我的线上导航：https://mnn.xyz

使用的版本是0.0.7

**Comment by Yakumo-Yukari** [comment]
> ![image](https://user-images.githubusercontent.com/23377279/105575634-071a8700-5da8-11eb-947e-d27b67285054.png)
> 
> 0.6可能是cdn有缓存 需要时0.7才对 安装的是0.8其实这个值也是0.7，0.8只是改了readme，version我给忘了~
> 
> 你能给一个线上demo我看看 我这边测起来是正常的

在edge chrome下没问题 在firefox下就可以进入查看器和网络

**Comment by theajack** [comment]
@Yakumo-Yukari 
谢谢你的反馈让我解决了这一个bug！这次应该已经修复了，请升级到 0.1.0使用。
IE,360,qq,FireFox,Chrome,Edge较新版本我都测了一遍，先开devtool后进入页面和先进页面后开devtool也都测了。
不过毕竟是偏门左道，对于低版本浏览器还是可能不生效的
