### ISSUE TITLE
npm包中的类型声明和文档不一致

### ISSUE THREAD

**Issue by A1len-L** [theajack/disable-devtool#41]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/24272981/181434392-f84e89d6-568b-4f90-a7b2-23fb53729f7a.png">
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/24272981/181434519-1c4e93cd-9bcc-4cda-bacc-6e114a9bf021.png">
npm包中的 DETECTOR_TYPE 缺少5；
detectors 也不是可选的。

**Comment by theajack** [comment]
Fixed in v0.3.0
