### ISSUE TITLE
先打开控制台，调成移动端模式，再输入网址，无法禁用

### ISSUE THREAD

**Issue by A1len-L** [theajack/disable-devtool#42]
<img width="1871" alt="image" src="https://user-images.githubusercontent.com/24272981/181437054-83b29a83-6004-4134-9609-dbe438d33561.png">

**Comment by wuyouw** [comment]
的确有这个问题，还希望能尽快修复

**Comment by Coaixy** [comment]
Thank you

**Comment by theajack** [comment]
可能新版本浏览器某些特性不支持了 后续我看看有没有其他方案

**Comment by theajack** [comment]
@wuyouw @A1len-L @Coaixy 
Now it works again in new version 0.2.6, please check it again.
