### ISSUE TITLE
Possible bug detected with DevTools window size

### ISSUE THREAD

**Issue by hijuuijj** [theajack/disable-devtool#44]
Many times this tool doesn't work. In my case, the way to fix it is simply by adjusting the size of the DevTools window (from the vertical line between the browser and DevTools). Then the window disappears.
When the size of DevTools is small this tool usually doesn't work.

**Comment by hijuuijj** [comment]
Confirmed. If the Devtool window is sized at minimum, the disable-DevTool does not work.

**Comment by theajack** [comment]
@hijuuijj @hankaibo 
Now it works again in new version 0.2.6, please check it again.
