### ISSUE TITLE
emmm我只想知道这是特性吗？

### ISSUE THREAD

**Issue by SUNWUYUAN** [theajack/disable-devtool#45]
emmm我只想知道这是特性吗？
![image](https://user-images.githubusercontent.com/88357633/184054108-65361f6a-626a-4d6b-a060-a7aa183149a1.png)
![image](https://user-images.githubusercontent.com/88357633/184054066-14a380cb-fa15-466b-8a4c-f7cf2d18e856.png)
emmm.....

**Comment by theajack** [comment]
可能浏览器新版本某些检测的方案不支持了

**Comment by SUNWUYUAN** [comment]
![image](https://user-images.githubusercontent.com/88357633/185781100-c38d7e24-6a74-4c0d-990d-22815a836f37.png)
emmm，这个项目需要更新了

**Comment by theajack** [comment]
@qihaimi @SUNWUYUAN @hankaibo 

Now it works again in new version 0.2.6, please check it again.
