### ISSUE TITLE
大佬升级到0.1.0后 用QQ浏览器访问 会直接关闭网页

### ISSUE THREAD

**Issue by Yakumo-Yukari** [theajack/disable-devtool#5]
有时候不会关闭 有时候一访问就直接关闭网页了  不知道怎么回事

**Comment by theajack** [comment]
我试过是没问题的啊
你用的什么版本的qq浏览器
再升到0.1.1试试 我优化了一点

**Comment by Yakumo-Yukari** [comment]
> 我试过是没问题的啊
> 你用的什么版本的qq浏览器
> 再升到0.1.1试试 我优化了一点

版本是：QQ浏览器10.7（4313）

**Comment by theajack** [comment]
那奇怪了 和我版本一样啊 你进这个页面会自己关闭或者跳走吗 https://theajack.gitee.io/disable-devtool/
![image](https://user-images.githubusercontent.com/23377279/105788994-8680a400-5fbc-11eb-8b7a-a32f2b828842.png)

**Comment by theajack** [comment]
@Yakumo-Yukari 是不是你打开了开发者工具并且分离了的情况下进入的

**Comment by Yakumo-Yukari** [comment]
> @Yakumo-Yukari 是不是你打开了开发者工具并且分离了的情况下进入的

没有打开开发这工具   就是正常访问  有时候在第一个标签里有访问的网站在第二个标签页里正常访问就会被自动关闭  有时候在第一个标签页里也会自动关闭    我等下试试0.1.1

**Comment by Yakumo-Yukari** [comment]
试了下0.1.1  还是会自动关闭 好奇怪啊

**Comment by xueyanruby** [comment]
难受，线上bug，0.3.7还是会跳 https://theajack.gitee.io/disable-devtool/；
