### ISSUE TITLE
Window.close rerect to dead URL: https://tackchen.gitee.io

### ISSUE THREAD

**Issue by davidgrayland** [theajack/disable-devtool#51]
Hi,

Why does it redirect to a dead URL 'https://tackchen.gitee.io'. Could this be amended to google search?

line 28
https://github.com/theajack/disable-devtool/blob/master/src/utils/close-window.ts

Thanks

**Comment by theajack** [comment]
Because Google cannot be reached in some country or area, You can set your custom url like this:

```js
DisableDevtool({
    url: 'https://www.google.com'
})
```

or 

```html
<script disable-devtool-auto url='https://www.google.com' src='https://cdn.jsdelivr.net/npm/disable-devtool'></script>
```

**Comment by davidgrayland** [comment]
👍
