### ISSUE TITLE
Issue Chrome iOS/iPhone Bypass

### ISSUE THREAD

**Issue by DeletedByAccident** [theajack/disable-devtool#59]
Chrome Version 113.0.5672.93 (Official Build) (64-bit)

1. Open a chrome window
2. Open dev tools
3. Set Dimensions to: iPhone SE, XR or 12 Pro
4. Visit the protected page
5. Result in infinite console output loop and never redirects or closes page

iPad Air, iPad Mini and none of the Android's are affected.
Also, no issue if you enter the page with devtools closed -> Then open dev tools from browser's triple dot menu.
![debug](https://github.com/theajack/disable-devtool/assets/61426176/54f0cde1-c3ee-4669-a42d-9ea7b58b7737)

**Comment by theajack** [comment]
Thanks for pointing it out! Fix in next version

**Comment by theajack** [comment]
fixed in v0.3.5

**Comment by theajack** [comment]
@DeletedByAccident
