### ISSUE TITLE
请问在nuxt.js里要怎么配置使用？

### ISSUE THREAD

**Issue by LolitaSquad** [theajack/disable-devtool#6]

**Comment by theajack** [comment]
这个与框架无关的 只要在web环境下都可以使用的

npm 安装使用：

```js
import disableDevtool from 'disable-devtool';

disableDevtool();
```

cdn方式使用
```html
<script disable-devtool-auto src='https://cdn.jsdelivr.net/npm/disable-devtool/disable-devtool.min.js'></script>
```

**Comment by LolitaSquad** [comment]
> 这个与框架无关的 只要在web环境下都可以使用的
> 
> npm 安装使用：
> 
> ```js
> import disableDevtool from 'disable-devtool';
> 
> disableDevtool();
> ```
> 
> cdn方式使用
> 
> ```
> <script disable-devtool-auto src='https://cdn.jsdelivr.net/npm/disable-devtool/disable-devtool.min.js'></script>
> ```

OK   果然  直接使用就可以了 我还以为要弄成插件去注册   谢谢解答

**Comment by theajack** [comment]
@LolitaSquad 

可以看看详细的 [参数使用](https://github.com/theajack/disable-devtool/blob/master/README.cn.md#31-npm%E4%BD%BF%E7%94%A8%E6%97%B6%E7%9A%84%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0)

**Comment by LolitaSquad** [comment]
> @LolitaSquad
> 
> 可以看看详细的 [参数使用](https://github.com/theajack/disable-devtool/blob/master/README.cn.md#31-npm%E4%BD%BF%E7%94%A8%E6%97%B6%E7%9A%84%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0)




在第一次使用正常可以看到效果  但是  一刷新页面就会报错  请问这种情况怎么解决
![屏幕截图 2021-02-23 14 32 12](https://user-images.githubusercontent.com/72801242/108809591-2a716580-75e4-11eb-8fb6-f517c5f37856.png)

**Comment by theajack** [comment]
@LolitaSquad 
你应该是把这个放在服务端渲染的逻辑里了 试着放在客户端渲染执行的地方

**Comment by theajack** [comment]
@LolitaSquad 

我加了一下 document的判断 你升级到 1.1.2 在服务端渲染里就应该也可以正常使用了

**Comment by LolitaSquad** [comment]
> @LolitaSquad
> 
> 我加了一下 document的判断 你升级到 1.1.2 在服务端渲染里就应该也可以正常使用了

好的   等你弄好了我升级一下

**Comment by theajack** [comment]
好了呀 已经发布1.1.2了

**Comment by LolitaSquad** [comment]
> 好了呀 已经发布1.1.2了

我去试试

**Comment by LolitaSquad** [comment]
![屏幕截图 2021-02-23 14 47 11](https://user-images.githubusercontent.com/72801242/108810553-58f04000-75e6-11eb-985a-bef763e768d2.png)

` "dependencies": {
    "@nuxtjs/axios": "^5.13.1",
    "core-js": "^3.8.3",
    "disable-devtool": "^0.1.2",
    "nuxt": "^2.14.12",
    "swiper": "5.x",
    "vue-awesome-swiper": "^4.1.1"
  },`

还是不行 我已经升级到0.1.2了  现在报窗口未定义

**Comment by theajack** [comment]
那这个就需要在客户端渲染调用了 这个是你调用 `disableDevtool();` 之后执行的
把这个调用 放在客户端渲染去做

**Comment by theajack** [comment]
或者放在 某个入口 vue 文件的 mounted 里去做

**Comment by LolitaSquad** [comment]
> 或者放在 某个入口 vue 文件的 mounted 里去做

` plugins: [
    { src: "@/plugins/disable-devtool", ssr: false }

  ],`

解决了 我注册成插件使用就可以了   直接使用还是会出现问题 注册成插件就可以了

**Comment by theajack** [comment]
ssr: false
 
 应该就是这个配置 没有在服务端调用

**Comment by LolitaSquad** [comment]
> ssr: false
> 
> 应该就是这个配置 没有在服务端调用

嗯   谢谢你的耐心解答
