### ISSUE TITLE
normal sidebars flag detection.

### ISSUE THREAD

**Issue by wagyourtail** [theajack/disable-devtool#60]
I use tree style tabs in firefox, it's a plugin that adds a sidebar for my tabs list.
this causes a false flag of the devtools detections... 

this can also be achieved with the bookmarks/history sidebars,
as well as by pinning any sidebar on Opera.
and the side panel on chrome

type = 2

**Comment by theajack** [comment]
Thanks for pointing it out! The next version considers removing the size detector, after all it is not so effective

**Comment by theajack** [comment]
fixed in v0.3.5
