### ISSUE TITLE
Super easy to bypass

### ISSUE THREAD

**Issue by TechGeekUnited** [theajack/disable-devtool#64]
You can just bypass it by setting a bookmarks url to 

"javascript:(function() {   var pageCode = document.documentElement.innerHTML;   var modifiedCode = pageCode.replace(/<script\b[^<]*(?:(?!%3C\/script%3E)%3C[^%3C]*)*%3C\/script%3E|%3Cscript|script%3E/gi,%20%27%27);%20%20%20document.open();%20%20%20document.write(modifiedCode);%20%20%20document.close();%20})();" 

And that disables it and you are free to do whatever you want.

**Comment by Gautam-Pra** [comment]
Not working
Unable to bypass with this method 
Tried in chrome ,brave and edge

**Comment by Gautam-Pra** [comment]
> It worked in my chromium based Browser (I used avast or pure chromium depends on the day).

Which browser??
Name it

**Comment by theajack** [comment]
As I said before, from a developer's point of view, this tool doesn't work in many ways. The most typical is to capture packets through the network and disable javascript functions
