### ISSUE TITLE
question: why should disable this tool for seo?

### ISSUE THREAD

**Issue by gyhyfj** [theajack/disable-devtool#72]
It seems that this tool just forbid user client inspect behavior, so why should disable this tool for crawler?

**Comment by theajack** [comment]
@gyhyfj If it is not prohibited, it may affect the website's SEO score and website performance score.

**Comment by gyhyfj** [comment]
Yes, performance score may decrease because of `setIntervail` and some other related code, is there anything else would affect SEO score?

**Comment by theajack** [comment]
@gyhyfj Because it may affect the access of SEO robots
