### ISSUE TITLE
Copy/paste not available in mobile browsers

### ISSUE THREAD

**Issue by jeffersonveloso** [theajack/disable-devtool#78]
I'm using the latest version of disable-devtool in the angular project.

Copy, paste, and select text is not available in mobile browsers. It happened on android and ios.

**Comment by theajack** [comment]
@jeffersonveloso Thanks for your feedback! I did find that the copy and paste button will not pop up after selecting the text. I will try to find the problem and solve it.

**Comment by theajack** [comment]
@jeffersonveloso This problem is solved in 0.3.7, please upgrade to this version to use
