### ISSUE TITLE
disableMenu参数chrome无效

### ISSUE THREAD

**Issue by x8845723** [theajack/disable-devtool#8]
RT

**Comment by theajack** [comment]
disableMenu 参数 表示 是否禁用右键菜单 默认为true
我这边试了不传或者传 false，可以禁用右键菜单，传false，不会阻止右键菜单

你是怎么调用的贴一下，怎么无效详细描述一下
@x8845723

**Comment by theajack** [comment]
disableMenu 参数 表示 是否禁用右键菜单 默认为true
我这边试了不传或者传 true，可以禁用右键菜单，传false，不会阻止右键菜单

你是怎么调用的贴一下，怎么无效详细描述一下
@x8845723

**Comment by theajack** [comment]
@x8845723 
感谢反馈 已修复 请升级到 0.1.3 使用
