### ISSUE TITLE
Something wrong with the code

### ISSUE THREAD

**Issue by glendstp** [theajack/disable-devtool#84]
Hello, the code is worked perfectly before but when I try to open the devtool again on my own website its doesn't close the page, and the only work is when the website is loaded and open the devtool and refresh its pausing the debugger, well I'm using Brave Browser (Version 1.62.165 Chromium: 121.0.6167.184)

![image](https://github.com/theajack/disable-devtool/assets/94733418/921a7513-5ada-4a53-9f28-72872b32a1f1)

**Comment by reidsneo** [comment]
For me when UBlock Origin ON same issue occured, adsblock plugin make the lib not working

**Comment by theajack** [comment]
This is because the js file loading is blocked, and bugs that do not belong to the code can be referenced through import instead of introducing a third-party CDN. But it cannot prevent the disabling failure problem caused by disabling all js
@reidsneo

**Comment by reidsneo** [comment]
> This is because the js file loading is blocked, and bugs that do not belong to the code can be referenced through import instead of introducing a third-party CDN. But it cannot prevent the disabling failure problem caused by disabling all js
> @reidsneo 

Yes that I want to say, thanks for the clarification
Somehow dev and debug like string got caught by the ads blocker, so it wont loaded

**Comment by glendstp** [comment]
@theajack I tried to import the code instead using the CDN even the CDN version is still work like when I open the dev-tool before visiting the website it's will prevent me to load the website properly but the non-CDN version is didn't do same thing, sorry for my terrible English & I'm a beginner on coding so I probably did something wrong?

![image](https://github.com/theajack/disable-devtool/assets/94733418/59900929-5dce-477b-a6d0-64daa6323663)

![image](https://github.com/theajack/disable-devtool/assets/94733418/ef5d603e-5050-4321-93a0-1c1298f410f6)
